ALTER TABLE "WishlistItem"
ADD COLUMN "kind" TEXT NOT NULL DEFAULT 'PURCHASE',
ADD COLUMN "savedAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "allocationAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "allocationMonth" INTEGER,
ADD COLUMN "allocationYear" INTEGER,
ADD COLUMN "completed" BOOLEAN NOT NULL DEFAULT false;
